# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/german/UnrealEngine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	Ludum58-Android-DebugGame  \
	Ludum58-Android-Development  \
	Ludum58-Android-Shipping  \
	Ludum58-Linux-DebugGame  \
	Ludum58-Linux-Development  \
	Ludum58-Linux-Shipping  \
	Ludum58-LinuxArm64-DebugGame  \
	Ludum58-LinuxArm64-Development  \
	Ludum58-LinuxArm64-Shipping  \
	Ludum58 \
	Ludum58Editor-Linux-DebugGame  \
	Ludum58Editor-Linux-Development  \
	Ludum58Editor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Ludum58Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Ludum58Editor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

Ludum58-Android-DebugGame:
	 $(BUILD) Ludum58 Android DebugGame  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-Android-Development:
	 $(BUILD) Ludum58 Android Development  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-Android-Shipping:
	 $(BUILD) Ludum58 Android Shipping  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-Linux-DebugGame:
	 $(BUILD) Ludum58 Linux DebugGame  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-Linux-Development:
	 $(BUILD) Ludum58 Linux Development  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-Linux-Shipping:
	 $(BUILD) Ludum58 Linux Shipping  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-LinuxArm64-DebugGame:
	 $(BUILD) Ludum58 LinuxArm64 DebugGame  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-LinuxArm64-Development:
	 $(BUILD) Ludum58 LinuxArm64 Development  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58-LinuxArm64-Shipping:
	 $(BUILD) Ludum58 LinuxArm64 Shipping  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58: Ludum58-Linux-Development

Ludum58Editor-Linux-DebugGame:
	 $(BUILD) Ludum58Editor Linux DebugGame  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58Editor-Linux-Development:
	 $(BUILD) Ludum58Editor Linux Development  -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" $(ARGS)

Ludum58Editor: Ludum58Editor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/german/UnrealProjects/Ludum58/Ludum58.uproject" -Game 

.PHONY: $(TARGETS)
